## -----------------------------------------------------------------------------
## github.com/balacode/udpt                                     /[.golangci.yml]
## (c) balarabe@protonmail.com                                      License: MIT
## -----------------------------------------------------------------------------

linters-settings:
    lll:
        line-length: 80

linters:
    # disable-all: true
    enable:
        - bodyclose
        - deadcode
        - depguard
        - dogsled
        - dupl
        - errcheck
        - exhaustive
        - funlen
        - gas
        - gochecknoinits
        - goconst
        - gocritic
        - gocyclo
        - gofmt
        - goimports
        - golint
        - goprintffuncname
        - gosec
        - gosimple
        - govet
        - ineffassign
        - lll
        - megacheck
        - misspell
        - nakedret
        - noctx
        - nolintlint
        - rowserrcheck
        - staticcheck
        - structcheck
        - stylecheck
        - typecheck
        - unconvert
        - unparam
        - unused
        - varcheck
        - whitespace
    disable:
        - gomnd      # magic numbers
        - interfacer # deprecated
        - maligned   # deprecated
        - scopelint  # deprecated

## end
